name: Test
on:
  pull_request:
    branches: [next]
jobs:
  test:
    name: Test
    runs-on: macos-11
    env:
      WORKING_DIRECTORY: ./apps/calendar
    steps:
      - name: Checkout next branch
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install -g npm
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Seoul
      - name: npm install(jest)
        run: |
          npm install
      - name: bootstrap packages
        run: |
          npx lerna bootstrap --no-ci
      - name: install playwright dependencies
        run: |
          npx playwright install
      - name: run unit test
        run: |
          npm run test
      - name: run E2E test
        run: |
          npm run test:playwright:ci
